### PR TITLE
First version of NMF solution

### PR DESCRIPTION
**Pull request by georghinkel**
Unfortunately, NMF has some problems resolving naming conflicts. In particular, the Children property that is used in the Tree metamodel example is a reserved term in NMF, which is why the generated code does not compile, currently. I will try to come up with a fix for that, but not sure I can make that today.

Families2Persons works. Second level tasks not yet implemented.

### CODE REVIEW

**Comment by agarciadom** [comment]
In case it helps, we've recently extended the deadline to 6pm :-).

**Comment by georghinkel** [comment]
Steps to run the solution:
1. Have MSBuild on your path (on my machine, C:\Program Files (x86)\MSBuild\14.0\Bin)
2. Build the project (MSBuild DataflowGenerator.csproj /p:Configuration=Release). Alternatively, you can use Visual Studio to do that (but not required)
3. Run the solution (it is located in bin\Release), simply passing the file location of the launch configuration

**Comment by agarciadom** [comment]
Could you provide binaries? I don't have Visual Studio, and many attendees won't. Does it work on Mono?

**Comment by georghinkel** [comment]
I will upload the binaries shortly. Mono is not supported since I am using MSBuild to compile my generated transformation on the fly and as far as I know, that is not running on Linux.

**Comment by georghinkel** [comment]
But as I described, you don't really need Visual Studio, the build tools suffice and as far as I am aware, these ship already with the .NET framework (but not 100% sure about that).

**Comment by agarciadom** [comment]
Thanks! Please don't forget to prepare slides for a 10 minute presentation on your particular solution.

**Pull request merged**
